// Static YouTube video catalog for the news site. These are curated embeds,
// not backend content — ported verbatim from the prototype (VIDEO_NEWS).
export const VIDEO_NEWS = [
    { id: 'v1', titulo: 'Colombia clasifica al Mundial 2026: la noche que paralizó al país', categoria: 'DEPORTES', autor: 'Redacción Deportes', fecha: '4 de septiembre de 2025', youtubeId: 'Cz2xm4VWzJE', link: 'https://www.youtube.com/watch?v=Cz2xm4VWzJE', resumen: 'Resumen y goles del partido Colombia vs Bolivia. La Selección goleó 3-0 y selló su clasificación al Mundial 2026.' },
    { id: 'v2', titulo: 'Resumen del clásico Nacional vs Cali 2026', categoria: 'DEPORTES', autor: 'Redacción Deportes', fecha: '9 de agosto de 2025', youtubeId: '2BM1ImeIjSc', link: 'https://www.youtube.com/watch?v=2BM1ImeIjSc', resumen: 'Todos los goles y las mejores jugadas del clásico del Valle entre Atlético Nacional y Deportivo Cali.' },
    { id: 'v3', titulo: 'Deportivo Cali vs La Equidad: resumen Liga BetPlay 2025', categoria: 'DEPORTES', autor: 'Juan López', fecha: '18 de mayo de 2025', youtubeId: 'fi7rsOd16Gw', link: 'https://www.youtube.com/watch?v=fi7rsOd16Gw', resumen: 'Resumen completo del partido entre Deportivo Cali y La Equidad por la Liga Colombiana 2025-I.' },
    { id: 'v4', titulo: 'Análisis del calendario de Colombia en el Mundial 2026', categoria: 'DEPORTES', autor: 'Redacción Deportes', fecha: '15 de agosto de 2025', youtubeId: 'xNjh-wQ07Cw', link: 'https://www.youtube.com/watch?v=xNjh-wQ07Cw', resumen: 'Un análisis de los rivales, fechas y clave para que Colombia avance en la Copa del Mundo.' },
    { id: 'v5', titulo: 'Colombia vs Perú: eliminatorias al Mundial 2026', categoria: 'DEPORTES', autor: 'Redacción Deportes', fecha: '15 de septiembre de 2025', youtubeId: 'aNbCHHqnakw', link: 'https://www.youtube.com/watch?v=aNbCHHqnakw', resumen: 'Resumen y análisis del partido Colombia vs Perú por las eliminatorias sudamericanas rumbo al Mundial 2026.' },
    { id: 'v6', titulo: 'Golazo histórico de James Rodríguez en la jornada de eliminatorias', categoria: 'DEPORTES', autor: 'Redacción Deportes', fecha: '22 de junio de 2025', youtubeId: 'UvdFN_-IMw8', link: 'https://www.youtube.com/watch?v=UvdFN_-IMw8', resumen: 'La jugada, el gol y la celebración de James Rodríguez en el triunfo que puso a Colombia en ventaja.' },
    { id: 'v7', titulo: 'Club América presenta nuevo técnico con vista al Mundial 2026', categoria: 'DEPORTES', autor: 'Redacción Deportes', fecha: '10 de septiembre de 2025', youtubeId: 'lHYHWwefArQ', link: 'https://www.youtube.com/watch?v=lHYHWwefArQ', resumen: 'El club anuncia su nuevo entrenador y su plan para llegar con jugadores en forma al Mundial.' },
    { id: 'v8', titulo: 'Colombia lista para el Mundial 2026: análisis y expectativas', categoria: 'DEPORTES', autor: 'Redacción Deportes', fecha: '20 de septiembre de 2025', youtubeId: '3HH4fmm6mhs', link: 'https://www.youtube.com/watch?v=3HH4fmm6mhs', resumen: 'Análisis completo de la Selección Colombia rumbo al Mundial 2026: figuras, estadísticas y expectativas.' },
    { id: 'v9', titulo: 'Preview de la Copa América Sub-23 2026', categoria: 'DEPORTES', autor: 'Redacción Deportes', fecha: '14 de septiembre de 2025', youtubeId: '3x2BH_gFy2s', link: 'https://www.youtube.com/watch?v=3x2BH_gFy2s', resumen: 'Los mejores talentos juveniles del continente se preparan para el torneo que puede definir su futuro.' },
    { id: 'v10', titulo: 'Final de la Liga BetPlay 2026: los goles del título', categoria: 'DEPORTES', autor: 'Redacción Deportes', fecha: '5 de julio de 2025', youtubeId: 'A_U4kO9m788', link: 'https://www.youtube.com/watch?v=A_U4kO9m788', resumen: 'Las mejores anotaciones y el festejo del campeón de la Liga BetPlay 2026.' },
    { id: 'v11', titulo: 'Selección Colombia femenina se prepara para el Mundial', categoria: 'DEPORTES', autor: 'Redacción Deportes', fecha: '24 de septiembre de 2025', youtubeId: '-XLb-PiUGuo', link: 'https://www.youtube.com/watch?v=-XLb-PiUGuo', resumen: 'Entrenamientos, convocadas y expectativas de la selección femenina rumbo a la Copa del Mundo.' },
    { id: 'v12', titulo: 'Atletismo colombiano gana medalla en el Sudamericano 2026', categoria: 'DEPORTES', autor: 'Redacción Deportes', fecha: '30 de agosto de 2025', youtubeId: 'zeD_tU8J2l0', link: 'https://www.youtube.com/watch?v=zeD_tU8J2l0', resumen: 'La delegación colombiana celebró con una medalla de oro en los 400 metros planos.' },
];
