// Covers the decision logic of `npm run db:migrate:soft`. The DDL itself is
// Sequelize's; what matters here is that the script never *decides* to do
// something destructive.
const { test, describe } = require('node:test');
const assert = require('node:assert/strict');

const {
    parseArgs, columnDefinition, additionSafety, driftReport, tableNameOf, missingColumns,
} = require('../scripts/_lib/soft_schema');

const empty = async () => false;
const populated = async () => true;

describe('parseArgs', () => {
    test('sin argumentos: todos los modelos, sin dry-run', () => {
        assert.deepEqual(parseArgs([]), { dryRun: false, targets: [] });
    });

    test('separa flags de nombres de modelo', () => {
        assert.deepEqual(parseArgs(['Channel', '--dry-run', 'Video']), {
            dryRun: true,
            targets: ['Channel', 'Video'],
        });
    });
});

describe('additionSafety', () => {
    test('columna nullable: siempre segura', async () => {
        const result = await additionSafety({ allowNull: true }, populated);
        assert.equal(result.safe, true);
    });

    test('allowNull sin declarar equivale a nullable', async () => {
        const result = await additionSafety({}, populated);
        assert.equal(result.safe, true);
    });

    test('NOT NULL con default: segura aunque haya filas', async () => {
        const result = await additionSafety({ allowNull: false, defaultValue: 0 }, populated);
        assert.equal(result.safe, true);
    });

    test('NOT NULL con default falsy: sigue siendo un default', async () => {
        // El bug clásico: `if (attr.defaultValue)` trataría false/0/'' como
        // ausencia de default y bloquearía una columna perfectamente segura.
        for (const defaultValue of [false, 0, '']) {
            const result = await additionSafety({ allowNull: false, defaultValue }, populated);
            assert.equal(result.safe, true, `defaultValue=${JSON.stringify(defaultValue)}`);
        }
    });

    test('NOT NULL sin default y con filas: bloqueada', async () => {
        const result = await additionSafety({ allowNull: false }, populated);
        assert.equal(result.safe, false);
        assert.match(result.reason, /NOT NULL/);
    });

    test('NOT NULL sin default y tabla vacía: permitida', async () => {
        const result = await additionSafety({ allowNull: false }, empty);
        assert.equal(result.safe, true);
    });

    test('clave primaria: bloqueada incluso en tabla vacía', async () => {
        const result = await additionSafety({ primaryKey: true, allowNull: true }, empty);
        assert.equal(result.safe, false);
    });

    test('autoincremental: bloqueada', async () => {
        const result = await additionSafety({ autoIncrement: true, allowNull: true }, empty);
        assert.equal(result.safe, false);
    });
});

describe('columnDefinition', () => {
    test('conserva las claves de columna y descarta el ruido de Sequelize', () => {
        const definition = columnDefinition({
            type: 'STRING', allowNull: false, defaultValue: 'x', comment: 'c',
            Model: {}, fieldName: 'foo', field: 'foo', _autoGenerated: true,
        });
        assert.deepEqual(definition, {
            type: 'STRING', allowNull: false, defaultValue: 'x', comment: 'c',
        });
    });

    test('omite las claves ausentes en vez de mandarlas como undefined', () => {
        const definition = columnDefinition({ type: 'INTEGER' });
        assert.deepEqual(Object.keys(definition), ['type']);
        assert.equal('allowNull' in definition, false);
    });
});

describe('driftReport', () => {
    const model = {
        rawAttributes: {
            id:        { field: 'id' },
            createdAt: { field: 'created_at' },
            name:      { allowNull: false },
        },
    };

    test('detecta columnas huérfanas (borrarlas sería destructivo)', () => {
        const { orphaned } = driftReport(model, {
            id: {}, created_at: {}, name: {}, legacy_col: {},
        });
        assert.deepEqual(orphaned, ['legacy_col']);
    });

    test('compara por nombre de columna, no de atributo', () => {
        // createdAt -> created_at: mapear mal marcaría created_at como huérfana
        // y createdAt como faltante, provocando una columna duplicada.
        const { orphaned } = driftReport(model, { id: {}, created_at: {}, name: {} });
        assert.deepEqual(orphaned, []);
    });

    test('señala NOT NULL en el modelo contra NULL en la tabla', () => {
        const { retyped } = driftReport(model, {
            id: {}, created_at: {}, name: { allowNull: true },
        });
        assert.equal(retyped.length, 1);
        assert.equal(retyped[0].column, 'name');
    });
});

describe('missingColumns', () => {
    const model = {
        rawAttributes: {
            id:        { field: 'id' },
            logoPath:  { field: 'logo_path', allowNull: true },
            createdAt: { field: 'created_at' },
            name:      {},
        },
    };

    test('devuelve solo lo que falta, con el nombre de columna real', () => {
        const missing = missingColumns(model, { id: {}, created_at: {}, name: {} });
        assert.deepEqual(missing.map(m => m.column), ['logo_path']);
        assert.equal(missing[0].attribute.allowNull, true);
    });

    test('no reporta nada cuando la tabla ya está al día', () => {
        const missing = missingColumns(model, {
            id: {}, logo_path: {}, created_at: {}, name: {},
        });
        assert.deepEqual(missing, []);
    });

    test('usa el field mapeado, no el nombre del atributo', () => {
        // Con createdAt/created_at mal mapeado añadiría una columna duplicada
        // "createdAt" junto a la "created_at" que ya existe.
        const missing = missingColumns(model, { id: {}, logo_path: {}, name: {} });
        assert.deepEqual(missing.map(m => m.column), ['created_at']);
    });
});

describe('tableNameOf', () => {
    test('acepta el nombre como string', () => {
        assert.equal(tableNameOf({ getTableName: () => 'channels' }), 'channels');
    });

    test('acepta la forma { tableName, schema }', () => {
        assert.equal(
            tableNameOf({ getTableName: () => ({ tableName: 'channels', schema: 'public' }) }),
            'channels',
        );
    });
});
