// Decision logic for `npm run db:migrate:soft` — deliberately free of any
// database, env or logger import so it stays unit-testable (core/config/env.js
// exits the process when the env is incomplete, which would kill the runner).
//
// Nothing here executes DDL. These functions only decide what is safe.

// Attribute keys that describe the column itself. Everything else on a
// Sequelize rawAttributes entry is bookkeeping (Model, fieldName,
// _autoGenerated…) and must not be forwarded to addColumn.
const COLUMN_KEYS = [
    'type', 'allowNull', 'defaultValue', 'unique', 'comment',
    'references', 'onUpdate', 'onDelete',
];

function parseArgs(argv) {
    return {
        dryRun: argv.includes('--dry-run'),
        targets: argv.filter(arg => !arg.startsWith('--')),
    };
}

function tableNameOf(model) {
    const name = model.getTableName();
    return typeof name === 'string' ? name : name.tableName;
}

// Only the column definition keys, with absent ones omitted so Sequelize falls
// back to its own defaults instead of receiving explicit undefined.
function columnDefinition(attribute) {
    const definition = {};
    for (const key of COLUMN_KEYS) {
        if (attribute[key] !== undefined) definition[key] = attribute[key];
    }
    return definition;
}

// A column can be added without touching existing rows when it accepts NULL or
// carries a default. NOT NULL with no default only works on an empty table —
// Postgres has to put *something* in the rows that already exist.
// `tableHasRows` is injected so the decision is testable without a database.
async function additionSafety(attribute, tableHasRows) {
    if (attribute.primaryKey || attribute.autoIncrement) {
        return { safe: false, reason: 'es clave primaria / autoincremental: requiere migración explícita' };
    }
    if (attribute.allowNull !== false || attribute.defaultValue !== undefined) {
        return { safe: true };
    }
    if (await tableHasRows()) {
        return { safe: false, reason: 'NOT NULL sin defaultValue y la tabla tiene filas' };
    }
    return { safe: true };
}

// Everything the tool refuses to touch: reported so the output doubles as the
// to-do list for a real migration in scripts/migrations/.
function driftReport(model, description) {
    const declared = new Map(
        Object.entries(model.rawAttributes).map(([name, attr]) => [attr.field || name, attr])
    );

    const orphaned = Object.keys(description).filter(column => !declared.has(column));

    const retyped = [];
    for (const [column, attribute] of declared) {
        const current = description[column];
        if (!current) continue;
        if (attribute.allowNull === false && current.allowNull === true) {
            retyped.push({ column, change: 'el modelo la declara NOT NULL, la tabla la tiene NULL' });
        }
    }

    return { orphaned, retyped };
}

// Columns the model declares that the table does not have yet.
function missingColumns(model, description) {
    return Object.entries(model.rawAttributes)
        .map(([name, attribute]) => ({ column: attribute.field || name, attribute }))
        .filter(({ column }) => !description[column]);
}

module.exports = {
    COLUMN_KEYS, parseArgs, tableNameOf, columnDefinition,
    additionSafety, driftReport, missingColumns,
};
